version: "3.7"
services:
  web:
    build: ./nginx
    ports:
      - "${HTTP_PORT}:80"

  app:
    build: ./app
    volumes:
      - "./app/src:/app"
      - xhprof:/tmp/xhprof/

  database:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  xhprof:
    build: ./xhprof/
    volumes:
      - xhprof:/tmp/xhprof/
    ports:
      - 8080:80

volumes:
  mysql:
  xhprof: