version: "3.7"
services:
  web:
    build: ./nginx
    ports:
      - "${HTTP_PORT}:80"

  app:
    build: ./app
    volumes:
      - "./app/src:/app"
      - "./app/conf.d/xdebug.ini:/usr/local/etc/php/php.ini"
      - profile:/tmp/xdebug

  database:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  profile:
    image: jokkedk/webgrind
    volumes:
      - profile:/tmp
    ports:
      - "${PROFILE_PORT}:80"

volumes:
  mysql:
  profile: